Add MegaPrimeImage project
opencadc/notebook-ui pull request #17
Opened 2019-11-05 21:07 UTC by LiaoWenyun

2019-11-06 00:01 UTC, andamian requested changes

2019-11-06 00:01 UTC, andamian commented on MegaPrimeImage/megaPrimeImage.ipynb
> +    "    return ['background-color: %s ' % color] * len(row.values)\n",
This is very old school str formatting. Because you are using Python3.6 you could use fstrings throughout the code.

2019-11-06 00:01 UTC, andamian commented on MegaPrimeImage/megaPrimeImage.ipynb
> +    "        print(\"Number of record: {}\".format(subset_num_records[i]))\n",
Number of records - missing s.

2019-11-06 00:01 UTC, andamian commented on MegaPrimeImage/megaPrimeImage.ipynb
> +    "            style=widgets.ButtonStyle(button_color='#E58975'),\n",
Maybe create consts for colours in a colour schema section so that someone could easily change them later if they want to.

2019-11-06 00:01 UTC, andamian commented on MegaPrimeImage/megaPrimeImage.ipynb
> +    "def display_spinner(spinner):\n",
Wouldn't the spinner be a good candidate for a context manager?

2019-11-06 00:01 UTC, andamian commented on MegaPrimeImage/megaPrimeImage.ipynb
> +    "                spinner.value = False\n",
If spinner was a context manager you wouldn't have to think when to stop it.

2019-11-06 00:01 UTC, andamian commented on MegaPrimeImage/megaPrimeImage.ipynb
> +    "                return 0\n",
why `return 0`? Is this required by the widget framework? I don't see other values being returned?

2019-11-06 00:01 UTC, andamian commented on MegaPrimeImage/megaPrimeImage.ipynb
> +    "    output_file = 'tmp/test_vooutput.xml'\n",
Have you tried to make `output_file = BytesIO()` instead. Most of the times this avoids the creation of the temp file.

2019-11-06 00:01 UTC, andamian commented on MegaPrimeImage/megaPrimeImage.ipynb
> +    "    quality_query = \"\"\"SELECT Tmp.observationURI AS Preview,\n",
It might be faster if the `tmp` table contains the minimum, i.e. in this case just `observationID` and the join of the values from the 2 tables is done in the code after the second query returns. Not that you have to do it now but something to keep in mind.

2019-11-06 19:26 UTC, LiaoWenyun commented on MegaPrimeImage/megaPrimeImage.ipynb
> +    "    output_file = 'tmp/test_vooutput.xml'\n",
query() method only take the path to a file instead of a file handle . I did try to use a stringIO or a BytesIO but they didn't work.

2019-11-06 19:31 UTC, LiaoWenyun commented on MegaPrimeImage/megaPrimeImage.ipynb
> +    "                return 0\n",
I should be return None

2019-11-06 19:40 UTC, LiaoWenyun commented on MegaPrimeImage/megaPrimeImage.ipynb
> +    "        print(\"Number of record: {}\".format(subset_num_records[i]))\n",
fixed

2019-11-06 19:57 UTC, LiaoWenyun commented on MegaPrimeImage/megaPrimeImage.ipynb
> +    "    return ['background-color: %s ' % color] * len(row.values)\n",
fixed

2019-11-06 20:12 UTC, LiaoWenyun commented on MegaPrimeImage/megaPrimeImage.ipynb
> +    "            style=widgets.ButtonStyle(button_color='#E58975'),\n",
Fixed

2019-11-06 20:15 UTC, LiaoWenyun commented on MegaPrimeImage/megaPrimeImage.ipynb
> +    "                return 0\n",
fixed

2019-11-06 20:39 UTC, LiaoWenyun commented on MegaPrimeImage/megaPrimeImage.ipynb
> +    "def display_spinner(spinner):\n",
I'm not exactly sure about how should the context manager work. but I'll give it a try..

2019-11-06 22:24 UTC, LiaoWenyun commented on MegaPrimeImage/megaPrimeImage.ipynb
> +    "def display_spinner(spinner):\n",
Fixed. Created a context manager class 'Spinner' .

2020-01-07 01:36 UTC, andamian commented
@LiaoWenyun Happy New Year! Hope you've had a great vacation. 

I'm trying to merge this PR but the tests are failing with an incomplete error. I would be tempted to think that it's a networking problem except that it occurs at the same point. Any ideas?

2020-01-07 19:16 UTC, LiaoWenyun commented
It's the supernova project. The first time it happened was due to the tap server crash. It gave me a 500 internal server error,  then I changed the URL to argus instead of using tap.  It worked fine when I ran it locally or in a docker container.  I think the server is not giving a valid response.

2020-01-07 19:31 UTC, LiaoWenyun commented
happy new year to you too.

2020-01-07 19:43 UTC, LiaoWenyun commented
@andamian 
HTTPError: 500 Server Error: Internal Server Error for url: https://www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/argus/sync/iwrtk74b6sy4k8gt/run

something is wrong with the resource_id: 
client = CadcTapClient(anonSubject, resource_id='ivo://cadc.nrc.ca/argus')

2020-01-08 18:21 UTC, andamian commented
It's a different error now. I'm not aware of any problems with our services.

2020-01-09 06:15 UTC, LiaoWenyun commented
@andamian Fixed. The problem was due to the update of astropy and astroquery packages, to fix it I specified the version of the two packages.

2020-01-09 17:51 UTC, andamian approved these changes

2020-01-09 17:55 UTC, andamian commented
> @andamian Fixed. The problem was due to the update of astropy and astroquery packages, to fix it I specified the version of the two packages.

Thanks. I can now merge it although this is probably a temporary fix since the project should work with the latest version of `astropy`. Could I ask you another favour: can you open a github ticket in this project explaining the nature of the problem so that someone can have a look at it? Thanks

2020-01-09 17:55 UTC, merged